[2025-08-27T07:55:58.980+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-27T07:55:59.003+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_dag.create_bucket manual__2025-08-27T07:55:57.634136+00:00 [queued]>
[2025-08-27T07:55:59.009+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_dag.create_bucket manual__2025-08-27T07:55:57.634136+00:00 [queued]>
[2025-08-27T07:55:59.010+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-27T07:55:59.020+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_bucket> on 2025-08-27 07:55:57.634136+00:00
[2025-08-27T07:55:59.028+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bronze_dag', 'create_bucket', 'manual__2025-08-27T07:55:57.634136+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/bronze_dag.py', '--cfg-path', '/tmp/tmph56bsmw_']
[2025-08-27T07:55:59.029+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask create_bucket
[2025-08-27T07:55:59.030+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=720) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-27T07:55:59.030+0000] {standard_task_runner.py:63} INFO - Started process 722 to run task
[2025-08-27T07:55:59.073+0000] {task_command.py:426} INFO - Running <TaskInstance: bronze_dag.create_bucket manual__2025-08-27T07:55:57.634136+00:00 [running]> on host 5044b6ce699d
[2025-08-27T07:55:59.134+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bronze_dag' AIRFLOW_CTX_TASK_ID='create_bucket' AIRFLOW_CTX_EXECUTION_DATE='2025-08-27T07:55:57.634136+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-27T07:55:57.634136+00:00'
[2025-08-27T07:55:59.136+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-27T07:55:59.136+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-27T07:55:59.137+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: create_bucket_if_not_exists() missing 1 required positional argument: 'bucket_name'
[2025-08-27T07:55:59.144+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=bronze_dag, task_id=create_bucket, run_id=manual__2025-08-27T07:55:57.634136+00:00, execution_date=20250827T075557, start_date=20250827T075559, end_date=20250827T075559
[2025-08-27T07:55:59.152+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task create_bucket (create_bucket_if_not_exists() missing 1 required positional argument: 'bucket_name'; 722)
[2025-08-27T07:55:59.164+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-27T07:55:59.181+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-27T07:55:59.183+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
